Repository FRONTENDSCHOOL10/Samcho, pull requests merged in 2024-09, with the labels that each got.

#17 feat: TopNavigation 컴포넌트 마크업 / 스타일링 / 토글기능 구현 완료
  src/assets/icons/menu/Calendar2.svg
  src/assets/icons/menu/Filter.svg
  src/assets/icons/menu/List.svg
  src/assets/icons/menu/Search.svg
  src/assets/icons/menu/index.js
  src/components/index.js
  src/components/layouts/TopNavigation.jsx
Labels: 🎨 Html&css

#19 feat: TopHeader 컴포넌트 마크업 / 스타일링 완료
  src/assets/icons/direction/direction-down.svg
  src/assets/icons/direction/direction-left.svg
  src/assets/icons/direction/direction-right.svg
  src/assets/icons/direction/direction-up.svg
  src/assets/icons/direction/index.js
  src/components/index.js
  src/components/layouts/TopHeader.jsx
Labels: 🎨 Html&css

#21 feat: TextArea 컴포넌트 마크업 작업 및 GNB 내비게이션 작업
  package.json
  pnpm-lock.yaml
  src/components/atomic/TextArea.jsx
  src/components/index.js
  src/components/layouts/Footer.jsx
  src/components/layouts/TopHeader.jsx
  src/components/layouts/TopNavigation.jsx
  src/pages/Chart.jsx
  src/pages/Diary/DetailDiary.jsx
  src/pages/Diary/EditDiary.jsx
  src/pages/Diary/NewDiary.jsx
  src/pages/Home.jsx
  src/pages/Mypage.jsx
  src/pages/Post.jsx
  src/pages/index.js
  src/router.jsx
  src/styles/main.css
  tailwind.config.js
Labels: 🎨 Html&css

#18 feat: ToggleButton 컴포넌트 마크업/스타일링 완료
  src/components/atomic/ToggleButton.jsx
Labels: 🎨 Html&css

#24 feat: FeelingCalendar 컴포넌트 마크업 / 스타일링 완료
  src/assets/icons/mood/moodIcons.js
  src/components/atomic/FeelingCalendar.jsx
  src/components/index.js
Labels: 🎨 Html&css

#25 feat: 로그인 및 회원가입 페이지 마크업
  public/logo.png
  src/components/atomic/Button.jsx
  src/components/atomic/Input.jsx
  src/components/index.js
  src/components/layouts/TopHeader.jsx
  src/components/layouts/TopNavigation.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: 🎨 Html&css

#27 feat: EmotionDistribution 컴포넌트 마크업/스타일링 완료
  src/assets/icons/mood/index.js
  src/components/atomic/EmotionDistribution.jsx
  src/components/index.js
Labels: 🎨 Html&css

#29 feat: WeatherWithIcon 컴포넌트 마크업/스타일링 완료
  src/components/atomic/WeatherWithIcon.jsx
Labels: 🎨 Html&css

#31 feat: 연,월 선택 컴포넌트 마크업
  src/components/atomic/YearMonth.jsx
  src/components/index.js
  src/pages/Home.jsx
  src/styles/main.css
Labels: 🎨 Html&css

#32 feat: iconRank 마크업및 스타일링
  src/components/atomic/IconRank.jsx
Labels: 🎨 Html&css

#34 feat : MoodDistributionChart 몰레큘 컴포넌트 마크업/스타일링 완료
  src/components/atomic/MoodDistribution.jsx
  src/components/index.js
  src/components/molecule/MoodDistributionChart.jsx
Labels: 🎨 Html&css

#44 feat : IconRankMoreList 컴포넌트 마크업 완료
  src/components/atomic/IconRankMoreList.jsx
  src/components/index.js
  src/components/molecule/MoodDistributionChart.jsx
Labels: 🎨 Html&css

#45 feat: 캘린더 molecule 컴포넌트 마크업/스타일링, useCalendar 커스텀 훅 추가
  package.json
  pnpm-lock.yaml
  src/components/atomic/FeelingCalendar.jsx
  src/components/index.js
  src/components/molecule/Calendar.jsx
  src/hooks/useCalendar.jsx
Labels: 🎨 Html&css

#46 feat : mood analy sis and rank 컴포넌트 마크업 완료
  src/components/molecule/EmotionRanking.jsx
Labels: 🎨 Html&css

#48 feat : SelectPicture 컴포넌트 마크업 완료
  src/assets/icons/diary/camera.svg
  src/components/molecule/SelectPicture.jsx
Labels: 🎨 Html&css

#49 feat: Accordion 컴포넌트 마크업
  src/components/atomic/Accordion.jsx
  src/components/atomic/TextArea.jsx
  src/components/atomic/WeatherWithIcon.jsx
  src/components/index.js
  src/components/molecule/EmotionRanking.jsx
  src/components/molecule/SelectPicture.jsx
  src/pages/Chart.jsx
  src/pages/Diary/NewDiary.jsx
  src/styles/main.css
Labels: 🎨 Html&css

#52 feat: 감정 랭킹 더보기 페이지 마크업
  src/components/atomic/IconRankMoreList.jsx
  src/components/atomic/ToggleButton.jsx
  src/components/layouts/Footer.jsx
  src/pages/ChartMoreList.jsx
  src/pages/Home.jsx
Labels: 🎨 Html&css

#59 feat : ToggleTab 컴포넌트 마크업 완료
  src/components/atomic/ToggleTab.jsx
  src/components/index.js
Labels: 🎨 Html&css

#51 feat: SelectEmotion 컴포넌트 마크업
  src/components/atomic/SelectEmotion.jsx
Labels: 🎨 Html&css

#60 feat: PostCard 컴포넌트 마크업 완료
  src/assets/icons/postcard/check.svg
  src/assets/icons/postcard/delete.svg
  src/components/index.js
  src/components/molecule/PostCard.jsx
Labels: 🎨 Html&css

#61 feat: DiaryDetail 컴포넌트 마크업/스타일링 및 상태 관리 로직 추가
  src/assets/icons/menu/delete.svg
  src/assets/icons/menu/edit.svg
  src/assets/icons/menu/index.js
  src/components/molecule/DiaryDetail.jsx
Labels: ✨ Feature, 🎨 Html&css

#62 feat: MoodChart 컴포넌트 마크업
  package.json
  pnpm-lock.yaml
  src/api/pb.js
  src/components/index.js
  src/components/molecule/MoodChart.jsx
  src/pages/Chart.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
Labels: 🎨 Html&css

#66 feat : Post(우편함) 페이지 마크업 완료 및 컴포넌트 수정
  src/components/atomic/ToggleTab.jsx
  src/components/molecule/PostCard.jsx
  src/pages/Post.jsx
Labels: 🎨 Html&css, 🥰 Accessibility

#68 refactor: Button 컴포넌트 불필요한 코드 외부로 이동
  src/components/atomic/Button.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#69 refactor: Calendar 컴포넌트 불필요한 코드 외부로 이동 및 테이블 제목 요소 추가
  src/components/molecule/Calendar.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#72 refactor: TopNavigation 컴포넌트에 aria-label 추가
  src/components/layouts/TopNavigation.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#70 refactor : ToggleTab 컴포넌트 ARIA-접근성 리팩토링
  src/components/atomic/ToggleTab.jsx
  src/pages/Post.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#79 refactor: Input 컴포넌트 마크업 개선 및 리팩토링
  src/components/atomic/Input.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#81 refactor : MoodDistribution 컴포넌트 마크업 오류 수정
  src/components/atomic/MoodDistribution.jsx
Labels: 🔨 Refactor

#84 feat: 에러 페이지 구현 완료
  public/errorMong.png
  src/pages/ErrorPage.jsx
  src/pages/index.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Html&css

#73 feat: myPage 페이지 마크업 및 스타일링
  src/pages/Mypage.jsx
Labels: 🎨 Html&css

#77 refactor : EmotionRanking 마크업 접근성 개선 리팩토링
  package-lock.json
  src/components/molecule/EmotionRanking.jsx
  src/pages/MyPageSetting.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#86 feat: 일기 작성 페이지 마크업 및 컴포넌트 조합
  index.html
  public/icons/emotions/annoyed.png
  public/icons/emotions/anxious.png
  public/icons/emotions/ballon.png
  public/icons/emotions/calm.png
  public/icons/emotions/comfortable.png
  public/icons/emotions/flower.png
  public/icons/emotions/gift.png
  public/icons/emotions/gloomy.png
  public/icons/emotions/hoguma.png
  public/icons/emotions/juice.png
  public/icons/emotions/leaves.png
  public/icons/emotions/motivation.png
  public/icons/emotions/popper.png
  public/icons/emotions/pressure.png
  public/icons/emotions/proud.png
  public/icons/emotions/stressful.png
  public/icons/emotions/tears.png
  public/icons/emotions/thankful.png
  public/icons/emotions/tired.png
  public/icons/emotions/volcano.png
  public/icons/mood/BadMong.png
  public/icons/mood/HappyMong.png
  public/icons/mood/SadMong.png
  public/icons/mood/SmileMong.png
  public/icons/mood/SosoMong.png
  src/assets/icons/mood/BadMong.svg
  src/assets/icons/mood/HappyMong.svg
  src/assets/icons/mood/SadMong.svg
  src/assets/icons/mood/SmileMong.svg
  src/assets/icons/mood/SosoMong.svg
  src/assets/icons/mood/index.js
  src/components/atomic/Accordion.jsx
  src/components/atomic/SelectEmotion.jsx
  src/components/atomic/SelectMood.jsx
  src/components/atomic/TextArea.jsx
  src/components/atomic/WeatherWithIcon.jsx
  src/components/index.js
  src/components/layouts/TopHeader.jsx
  src/pages/Diary/DetailDiary.jsx
  src/pages/Diary/NewDiary.jsx
  src/pages/Home.jsx
  src/pages/Mypage.jsx
  src/router.jsx
Labels: 🎨 Html&css

#88 build: 빌드 배포간에 오류 해결
  src/assets/icons/menu/calendar2.svg
  src/assets/icons/menu/filter.svg
  src/assets/icons/menu/list.svg
  src/assets/icons/menu/search.svg
  src/styles/main.css
Labels: 🐞 BugFix, 🌏 Deploy

#89 feat: 계정관리 페이지 마크업/스타일링
  src/pages/MyPageSetting.jsx
Labels: 🎨 Html&css, 🔨 Refactor, 🥰 Accessibility

#92 bugfix : IconRankMoreList 컴포넌트 마크업 재설계
  src/components/atomic/IconRankMoreList.jsx
Labels: 🐞 BugFix, 🔨 Refactor, 🥰 Accessibility

#96 feat: 사진 모아보기 페이지 마크업 / 스타일링 완료
  src/components/molecule/Calendar.jsx
  src/hooks/index.js
  src/hooks/useFetchDiaryData.jsx
  src/pages/PhotoGallery.jsx
  src/pages/index.js
  src/router.jsx
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#116 refactor: 일기작성 페이지 마크업 수정
  src/components/common/Accordion.jsx
  src/pages/diary/NewDiary.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#117 buddyCard 컴포넌트 마크업 완료 & 단짝관리 페이지 마크업 및 수정 완료
  src/components/index.js
  src/pages/mypage/BuddyCard.jsx
  src/pages/mypage/BuddyManagement.jsx
Labels: 🎨 Html&css

#118 refactor: footer 레이아웃 컴포넌트 수정
  src/components/common/DiaryDetail.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/TopHeader.jsx
  src/pages/diary/DetailDiary.jsx
  src/pages/mypage/BuddyCard.jsx
  src/pages/mypage/BuddyManagement.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#119 refactor: Calendar 간격 수정
  src/components/home/Calendar.jsx
Labels: 🎨 Html&css

#120 refactor: 기분 아이콘 클릭 시 일기 상세로 이동 기능 구현 및 마크업/스타일링 수정
  src/components/common/DiaryDetail.jsx
  src/components/home/Calendar.jsx
  src/components/home/FeelingCalendar.jsx
  src/hooks/useCalendar.jsx
  src/pages/Home.jsx
  src/pages/diary/DetailDiary.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#121 refactor: DiaryCard 컴포넌트 피드백 관련 수정 및 웹 접근성 고려하여 마크업 구조 수정
  package-lock.json
  src/components/common/DiaryCard.jsx
  src/components/common/YearMonth.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/TopNavigation.jsx
  src/pages/Home.jsx
  src/styles/main.css
Labels: 🎨 Html&css, 🔨 Refactor

#122 refactor: YearMonth 컴포넌트 피드백 관련하여 수정
  src/components/common/YearMonth.jsx
  src/pages/chart/Chart.jsx
Labels: 🔨 Refactor

#123 우편함 페이지 마크업 수정 완료
  src/pages/Post.jsx
Labels: 🔨 Refactor

#124 refactor: 시멘틱 태그 및 웹접근성 피드백 관련 마크업 및 스타일링 수정
  src/components/chart/EmotionRankCard.jsx
  src/components/chart/EmotionRanking.jsx
  src/components/chart/MoodDistributionChart.jsx
  src/components/common/YearMonth.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#125 TopNavigation 컴포넌트 마크업 수정 완료
  src/assets/icons/menu/index.js
  src/assets/icons/menu/notification.svg
  src/components/layouts/TopNavigation.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#127 refactor: 스크롤 관련 웹 접근성 수정
  src/components/common/YearMonth.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/styles/main.css
Labels: 🎨 Html&css, 🔨 Refactor

#129 refactor: 날씨 이모티콘 변경 완료
  public/icons/weathers/cloudy.png
  public/icons/weathers/rainy.png
  public/icons/weathers/snowy.png
  public/icons/weathers/sunny.png
  public/icons/weathers/windy.png
Labels: 🔨 Refactor

#131 알림 페이지 마크업 및 NotificationCard 컴포넌트 마크업 완료
  src/assets/icons/notification/buddy.svg
  src/assets/icons/notification/exchangediary.svg
  src/components/index.js
  src/components/layouts/TopNavigation.jsx
  src/components/notification/NotificationCard.jsx
  src/pages/Notification.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🎨 Html&css

#132 refactor: moodchart 컴포넌트 2차 수정
  src/components/chart/EmotionRankCard.jsx
  src/components/chart/EmotionRanking.jsx
  src/components/chart/MoodChart.jsx
  src/components/chart/MoodDistributionChart.jsx
Labels: 🎨 Html&css

#133 feature: Modal 컴포넌트 마크업 및 hook 제작
  src/components/common/Modal.jsx
  src/components/index.js
  src/components/layouts/TopNavigation.jsx
  src/hooks/index.js
  src/hooks/useModal.js
Labels: ✨ Feature, 🎨 Html&css

#137 refactor: router 파일 변경
  src/components/layouts/Footer.jsx
  src/components/layouts/TopNavigation.jsx
  src/pages/Home.jsx
  src/router.jsx
Labels: 🔨 Refactor

#135 refactor: 커스텀 훅 분리 및 컴포넌트에서 날짜 선택 시 캘린더에 반영될 수 있도록 수정
  src/components/common/DiaryDetail.jsx
  src/components/home/Calendar.jsx
  src/components/home/FeelingCalendar.jsx
  src/hooks/index.js
  src/hooks/useCalendar.jsx
  src/hooks/useFetchAllDiaryData.jsx
  src/hooks/useFetchDiaryDetail.jsx
  src/hooks/useFetchMonthlyDiaryData.jsx
  src/pages/Home.jsx
  src/pages/diary/DetailDiary.jsx
  src/pages/mypage/PhotoGallery.jsx
  src/router.jsx
Labels: 🔨 Refactor

#138 feature: filter 컴포넌트 마크업 및 Select 컴포넌트 추가
  src/components/common/Modal.jsx
  src/components/common/Select.jsx
  src/components/index.js
  src/components/layouts/TopNavigation.jsx
  src/pages/Home.jsx
Labels: ✨ Feature, 🎨 Html&css

#139 feature: LoginAndRegister 회원가입 및 로그인, 로그아웃 기능 구현
  src/pages/auth/Login.jsx
  src/pages/auth/Register.jsx
  src/pages/mypage/MyPageSetting.jsx
  src/pages/mypage/Mypage.jsx
Labels: 📬 API, ✨ Feature

#144 refactor: 오류 및 오류 문구 props 추가
  src/components/chart/MoodChart.jsx
  src/components/common/Input.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Register.jsx
  src/utils/configRoutes.js
  src/utils/getNavigationItems.js
  src/utils/index.js
  src/utils/validation.js
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#157 feature: 다이어리 데이터 로그인한 사용자의 데이터만 가져오도록 수정
  src/hooks/useFetchAllDiaryData.jsx
  src/hooks/useFetchMonthlyDiaryData.jsx
Labels: 🔨 Refactor

#158 feat: 일기가 없는 날짜를 클릭하면 일기 작성 페이지로 이동할 수 있도록 구현
  src/components/home/FeelingCalendar.jsx
  src/components/newdiary/SelectMood.jsx
  src/pages/diary/DetailDiary.jsx
  src/pages/diary/NewDiary.jsx
  src/pages/index.js
  src/router.jsx
Labels: ✨ Feature

#159 feat : Input 컴포넌트 isViewIcon 추가 및 검증 성공 메세지 표시
  src/assets/icons/passwordView/invisible.svg
  src/assets/icons/passwordView/visible.svg
  src/components/common/Input.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Register.jsx
Labels: ✨ Feature, 🎨 Html&css

#164 feat: 단짝 관리 기능 구현
  src/hooks/useFetchBuddyData.jsx
  src/pages/mypage/BuddyCard.jsx
  src/pages/mypage/BuddyManagement.jsx
Labels: 📬 API, ✨ Feature

#166 feature: 다이어리 일기 작성 중간정도 구현 완료
  src/app/App.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/home/FeelingCalendar.jsx
  src/components/newdiary/SelectPicture.jsx
  src/components/newdiary/TextArea.jsx
  src/components/newdiary/WeatherWithIcon.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Register.jsx
  src/pages/diary/NewDiary.jsx
  src/pages/mypage/Mypage.jsx
Labels: 🐞 BugFix, 📬 API, ✨ Feature

#169 feature: 다이어리 일기 작성 구현 완료
  src/components/buddy/BuddyCard.jsx
  src/components/common/DiaryDetail.jsx
  src/components/index.js
  src/components/layouts/Footer.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Register.jsx
  src/pages/diary/NewDiary.jsx
  src/pages/mypage/Mypage.jsx
  src/router.jsx
Labels: 🐞 BugFix, 📬 API, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#170 feature: 감정랭킹 기능 구현
  src/components/chart/EmotionRankCard.jsx
  src/components/chart/EmotionRanking.jsx
  src/pages/chart/Chart.jsx
  src/pages/chart/ChartMoreList.jsx
Labels: 📬 API, ✨ Feature

#171 feature: 다이어리 카드 데이터 통신
  src/components/common/DiaryCard.jsx
  src/pages/Home.jsx
Labels: 📬 API

#172 feat: 검색 기능 및 검색기록 기능 구현
  src/assets/icons/menu/Calendar2.svg
  src/assets/icons/menu/Filter.svg
  src/assets/icons/menu/List.svg
  src/assets/icons/menu/Search.svg
  src/assets/icons/menu/close.svg
  src/assets/icons/menu/history.svg
  src/assets/icons/menu/index.js
  src/assets/icons/menu/search.svg
  src/components/index.js
  src/components/layouts/TopHeader.jsx
  src/components/layouts/TopNavigation.jsx
  src/components/searchdiary/SearchDiaryHistory.jsx
  src/components/searchdiary/SearchDiaryHistoryItem.jsx
  src/components/searchdiary/SearchDiaryInput.jsx
  src/pages/SearchDiary.jsx
  src/pages/index.js
  src/pages/mypage/BuddyManagement.jsx
  src/router.jsx
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#174 feat : 단짝 검색 및 신청 기능 구현 완료
  src/components/buddy/BuddySearch.jsx
  src/components/index.js
  src/pages/mypage/Mypage.jsx
Labels: 📬 API, ✨ Feature

#176 feat : 감정랭킹 리팩토링및 기분분포 기능 구현
  src/components/chart/EmotionRanking.jsx
  src/components/chart/MoodDistributionChart.jsx
  src/pages/chart/Chart.jsx
  src/pages/chart/ChartMoreList.jsx
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#178 feat: 기분 필터링 기능 추가
  src/pages/Home.jsx
Labels: ✨ Feature

#177 refactor: 일기 결과 월별 구분 및 일기 검색 리팩토링
  src/components/common/DiaryCard.jsx
  src/components/index.js
  src/components/searchdiary/SearchDiaryHistory.jsx
  src/components/searchdiary/SearchDiaryHistoryItem.jsx
  src/components/searchdiary/SearchDiaryInput.jsx
  src/components/searchdiary/SearchDiaryResult.jsx
  src/hooks/useFetchAllDiaryData.jsx
  src/pages/SearchDiary.jsx
  src/pages/mypage/PhotoGallery.jsx
  src/utils/groupByMonth.js
  src/utils/index.js
Labels: ✨ Feature, 🔨 Refactor

#180 refactor: EmotionRanking, EmotionRankCard , WeatherWithIcon 컴포넌트 수정
  src/components/chart/EmotionRankCard.jsx
  src/components/chart/EmotionRanking.jsx
  src/components/chart/MoodDistributionChart.jsx
  src/components/newdiary/WeatherWithIcon.jsx
  src/pages/mypage/Mypage.jsx
Labels: 🔨 Refactor

#182 refactor: 일기 수정, 삭제 기능 구현
  src/components/buddy/BuddySearch.jsx
  src/components/common/DiaryCard.jsx
  src/components/common/ToggleTab.jsx
  src/components/index.js
  src/components/newdiary/SelectPicture.jsx
  src/hooks/useFetchDiaryDetail.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/diary/NewDiary.jsx
  src/styles/main.css
Labels: ✨ Feature, 🔨 Refactor

#191 feat: 알림 기능 구현 완료
  src/components/notification/NotificationCard.jsx
  src/pages/Notification.jsx
Labels: 📬 API, ✨ Feature

#193 refactor : 단짝 검색 기능 - 아이디 & 닉네임으로 검색되도록 수정
  src/components/buddy/BuddySearch.jsx
  src/pages/mypage/Mypage.jsx
Labels: 🔨 Refactor

#199 modify : input 비밀번호 보기 관련 웹 접근성 수정
  src/components/common/Input.jsx
Labels: 🥰 Accessibility

#202 feat: 마이페이지 계정 관리 닉네임 변경 기능 구현
  src/pages/mypage/MyPageSetting.jsx
  src/pages/mypage/Mypage.jsx
Labels: 📬 API, ✨ Feature

#204 refactor : Input 컴포넌트 리펙토링
  src/components/common/Input.jsx
Labels: 🔨 Refactor

#207 refactor: 기분 필터링 컴포넌트 수정
  src/components/home/Calendar.jsx
  src/components/home/FeelingCalendar.jsx
  src/components/layouts/TopNavigation.jsx
  src/hooks/useCalendar.jsx
  src/pages/Home.jsx
Labels: 🔨 Refactor

#209 refactor: 일기 교환 기능 구현 및 교환 기능 전체 로직 수정
  src/components/buddy/BuddyCard.jsx
  src/components/buddy/BuddySearch.jsx
  src/components/common/CheckBox.jsx
  src/components/common/DiaryDetail.jsx
  src/components/index.js
  src/components/layouts/Footer.jsx
  src/hooks/index.js
  src/hooks/useFetchBuddyData.jsx
  src/pages/Notification.jsx
  src/pages/mypage/BuddyManagement.jsx
  src/pages/mypage/Mypage.jsx
  src/router.jsx
Labels: 🐞 BugFix, 📬 API, ✨ Feature, 🔨 Refactor

#210 bugFix: FeelingCalendar 컴포넌트에서 미래 날짜 클릭 오류 수정
  src/components/home/FeelingCalendar.jsx
Labels: 🐞 BugFix

#214 refactor: useFetchBuddyData 훅 수정
  src/components/common/DiaryDetail.jsx
  src/hooks/index.js
  src/hooks/useFetchAllBuddyData.jsx
  src/pages/mypage/BuddyManagement.jsx
  src/pages/mypage/Mypage.jsx
Labels: 🔨 Refactor

#215 feat: 마이페이지 올린 기록 개수 기능 구현
  src/pages/mypage/Mypage.jsx
Labels: 📬 API, ✨ Feature

#216 feat: 회원 탈퇴 기능 구현
  src/pages/mypage/MyPageSetting.jsx
Labels: 📬 API, ✨ Feature

#217 refactor: FeelingCalendar 컴포넌트에 loading 상태 추가 및 Calendar 컴포넌트로 렌더링 책임 이관
  src/components/home/Calendar.jsx
  src/components/home/FeelingCalendar.jsx
  src/hooks/useCalendar.jsx
  src/pages/Home.jsx
Labels: 🐞 BugFix, 🔨 Refactor

#218 modify : 회원가입 및 로그인 버튼 웹 접근성 수정
  src/components/common/Button.jsx
  src/pages/auth/Login.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#220 feature: post 페이지 교환일기 데이터 통신
  src/components/common/DiaryCard.jsx
  src/pages/Post.jsx
Labels: ✨ Feature

#221 refactor: TopNavigation 컴포넌트 접근성 관련 수정
  src/components/layouts/TopNavigation.jsx
  src/pages/Post.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#222 refactor: MoodDistributionChart 0% 렌더링 처리
  src/components/chart/MoodDistributionChart.jsx
Labels: 🔨 Refactor

#223 bugfix: 한국 시간 기준으로 계산이 되지 않았던점 수정
  src/pages/Notification.jsx
Labels: 🐞 BugFix

#227 refactor : 회원가입 페이지 기능 개선
  src/components/common/Input.jsx
  src/hooks/index.js
  src/hooks/useCheckAvailability.jsx
  src/pages/auth/Register.jsx
Labels: ✨ Feature, 🔨 Refactor

#238 bugfix : 단짝 찾기 엔터 키 리로드 버그 수정
  src/pages/mypage/Mypage.jsx
Labels: 🐞 BugFix, 🥰 Accessibility

#237 refactor: NewDiary 페이지에서 새로고침/뒤로가기 제어 및 useBlocker훅 추가
  src/components/common/Modal.jsx
  src/components/layouts/TopHeader.jsx
  src/hooks/index.js
  src/hooks/useBlocker.jsx
  src/pages/diary/NewDiary.jsx
  src/styles/main.css
Labels: 🔨 Refactor

#245 refactor: 일기 삭제, 교환, 수정 로직 hook 제작 하여 로직 분리
  src/components/chart/MoodDistributionChart.jsx
  src/components/common/BuddyListModal.jsx
  src/components/common/DiaryCard.jsx
  src/components/common/DiaryDetail.jsx
  src/components/index.js
  src/components/searchdiary/SearchDiaryResult.jsx
  src/hooks/index.js
  src/hooks/useDiaryActions.js
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/SearchDiary.jsx
  src/pages/diary/NewDiary.jsx
Labels: 🔨 Refactor

#247 feature: diarydtail 이미지 부분 스켈레톤 UI 적용
  src/components/common/DiaryDetail.jsx
Labels: ✨ Feature, 🎨 Html&css

#249 refactor: diarydetail 컴포넌트 내에서 일기 수정, 삭제 추가
  src/components/common/DiaryCard.jsx
  src/components/common/DiaryDetail.jsx
  src/hooks/useDiaryActions.js
Labels: 🔨 Refactor

#250 bugfix: 일기 작성 페이지 뒤로가기, 새로고침 관련 경고 삭제
  src/hooks/useFetchDiaryDetail.jsx
  src/pages/diary/NewDiary.jsx
Labels: 🐞 BugFix

#252 refactor: Modal 전체 너비 수정
  src/components/common/Modal.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#253 refactor: 메인 캘린더에서 오늘 날짜에 하이라이팅 처리
  src/assets/icons/daycircle/daycircle2.svg
  src/components/home/FeelingCalendar.jsx
Labels: 🔨 Refactor

#254 modify : 알림 페이지 로딩 문구, 데이터 없는 경우 문구 스타일링
  src/pages/Notification.jsx
Labels: 🎨 Html&css

#255 modify : 단짝관리 페이지 로딩문구 및 데이터가 없을 때 문구 스타일링 추가 & 단짝 1일 전인 경우 n시간으로 표시될 수 있도록 수정
  src/components/buddy/BuddyCard.jsx
  src/pages/mypage/BuddyManagement.jsx
Labels: 🔨 Refactor

#257 bugfix : 모달창 esc 키 눌렀을 때 '닫기' 기능 추가
  src/components/common/Modal.jsx
Labels: 🐞 BugFix

#258 modify : 회원 탈퇴 시 confirm 모달창 재스타일링 완료
  src/pages/mypage/MyPageSetting.jsx
Labels: 🎨 Html&css

#260 refactor: 로그인 페이지 로직 최적화 및 분리
  src/components/common/Button.jsx
  src/pages/auth/Login.jsx
  src/pages/mypage/MyPageSetting.jsx
  src/pages/mypage/Mypage.jsx
  src/utils/authUtils.js
  src/utils/index.js
Labels: 🔨 Refactor

#262 refactor: 교환된 일기는 수정, 삭제, 교환 버튼 disabled 처리 완료
  src/components/common/DiaryCard.jsx
  src/components/common/DiaryDetail.jsx
  src/pages/Post.jsx
  src/pages/diary/DetailDiary.jsx
Labels: 🔨 Refactor

#264 refactor: 확인 모달창 컴포넌트 제작 완료
  src/components/common/ConfirmModal.jsx
  src/components/common/DiaryCard.jsx
  src/components/common/DiaryDetail.jsx
  src/components/index.js
Labels: ✨ Feature

#266 refactor: 로그아웃 및 회원탈퇴 모달창 ConfirmModal 컴포넌트로 대체
  src/pages/mypage/MyPageSetting.jsx
Labels: 🔨 Refactor

#269 refactor: 일기작성 필수 입력값 데이터 통신 전 검증 되도록 수정
  src/hooks/useDiaryActions.js
Labels: 🔨 Refactor

#270 feat: 로딩 스피너 컴포넌트 추가 및 캘린더에 적용
  package.json
  pnpm-lock.yaml
  src/components/common/LoadingSpinner.jsx
  src/components/home/Calendar.jsx
  src/components/index.js
  src/pages/Home.jsx
Labels: ✨ Feature, 🔨 Refactor

#271 bugfix: 오늘 일기 작성한 경우 작성하기 버튼 누를시 경고창 표시
  src/components/common/LoadingSpinner.jsx
  src/components/layouts/Footer.jsx
  src/hooks/useDiaryActions.js
Labels: 🐞 BugFix, 🔨 Refactor

#272 bugfix: 일기 작성 중복 방지 로직 전체 수정
  src/components/layouts/Footer.jsx
  src/hooks/useDiaryActions.js
Labels: 🐞 BugFix, 🔨 Refactor

#273 refactor: 일기 상세페이지 교환된 일기일 경우 수정, 삭제, 교환 버튼 표시 안되도록 수정
  src/components/common/DiaryDetail.jsx
Labels: 🔨 Refactor

#274 refactor: 일기 검색 페이지에서 검색어를 URL 파라미터로 전달하도록 로직 수정
  src/components/searchdiary/SearchDiaryInput.jsx
  src/hooks/index.js
  src/hooks/useSearchDiary.js
  src/pages/SearchDiary.jsx
  src/pages/diary/DetailDiary.jsx
Labels: 🔨 Refactor

#275 Refactor/chart
  public/icons/emotions/default.png
  src/assets/icons/emotions/emotions.js
  src/components/chart/EmotionRankCard.jsx
  src/components/chart/EmotionRanking.jsx
  src/components/chart/MoodDistribution.jsx
  src/components/chart/MoodDistributionChart.jsx
Labels: 🎨 Html&css

#278 modify : 닉네임 변경 모달 중복으로 설정된 패딩 값 삭제
  src/pages/mypage/MyPageSetting.jsx
Labels: 🎨 Html&css

#283 bugfix : eslint 경고 수정 및 닉네임 변경 모달 레이아웃 수정
  src/pages/mypage/MyPageSetting.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#286 refactor: 기분 아이콘 중 '슬픔' 아이콘 교체
  public/icons/moods/sadmong.png
Labels: 🔨 Refactor

#294 bugfix: 사진 모아보기 페이지 로딩 상태 추가
  src/pages/mypage/PhotoGallery.jsx
Labels: 🐞 BugFix

#295 bugfix: 일기 작성시 비활성화된 버튼 활성화 안되는 점 수정
  src/hooks/useDiaryActions.js
Labels: 🐞 BugFix

#282 feat: 교환/단짝 신청 시 실시간 알림 구독 기능 추가
  src/components/layouts/TopNavigation.jsx
  src/hooks/index.js
  src/hooks/useNotification.js
  src/stores/index.js
  src/stores/notificationStore.js
Labels: ✨ Feature

#297 modify : 교환일기 수락할 때 일기가 많으면 일기를 스크롤할 수 있도록 스타일 수정
  src/pages/Notification.jsx
Labels: 🐞 BugFix

#298 feat: 페이지 이동 시 스크롤 위치 상단으로 고정하기 위한 ScrollToTop 훅 추가
  src/hooks/index.js
  src/hooks/useScrollToTop.jsx
  src/layouts/RootLayout.jsx
Labels: ✨ Feature

#302 refactor: 로그인한 사용자별로 고유한 검색 기록 저장되도록 로직 수정
  src/hooks/useSearchDiary.js
Labels: 🔨 Refactor

#303 feature : 교환일기 24시간 뒤 사라지도록 기능 구현 + DiaryCard에 경과시간 추가
  src/components/common/DiaryCard.jsx
  src/pages/Post.jsx
Labels: ✨ Feature, 🎨 Html&css

#308 design: 일기 검색 결과에서 DiaryCard 사이 간격 조정
  src/components/searchdiary/SearchDiaryResult.jsx
Labels: 🎨 Html&css

#311 modify : 상세다이어리 '교환하기' 버튼 & 알림페이지 모달창 '교환' 수락 버튼 비동기 진행중인 경우 비활성화
  src/components/common/BuddyListModal.jsx
  src/pages/Notification.jsx
Labels: ✨ Feature, 🎨 Html&css

#312 refactor: 일기 작성에서 한줄일기 글자 제한 부분 마크업 / 로직 수정
  src/components/newdiary/TextArea.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#321 bugfix : 닉네임 변경 시 유효성 검사 기능 추가 및 스타일링 수정
  src/pages/mypage/MyPageSetting.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#323 bugfix: 실시간 알림 처리 로직 수정
  src/stores/notificationStore.js
Labels: 🐞 BugFix, 🔨 Refactor

#325 bugfix: 단짝 관계 절교 시 교환일기 관련 알림 및 일기 데이터 삭제 처리
  src/components/buddy/BuddyCard.jsx
  src/hooks/useNotification.js
Labels: 🐞 BugFix

#326 refactor: 일기 작성 시, SelectPicture 컴포넌트에 키보드로 접근 가능하도록 로직 개선
  src/components/newdiary/SelectPicture.jsx
Labels: 🔨 Refactor, 🥰 Accessibility

#328 refactor : 탈퇴 기능 수정 완료
  src/components/common/ConfirmModal.jsx
  src/hooks/useFetchAllBuddyData.jsx
  src/pages/mypage/MyPageSetting.jsx
  src/utils/deletion.js
  src/utils/index.js
Labels: 🔨 Refactor

#330 bugfix: 일기 교환 로직 중 교환 버튼 활성화 조건 수정
  src/pages/Notification.jsx
Labels: 🐞 BugFix

#333 refactor : 토스트 메세지 전체적으로 수정
  src/components/buddy/BuddyCard.jsx
  src/components/buddy/BuddySearch.jsx
  src/components/common/BuddyListModal.jsx
  src/components/home/FeelingCalendar.jsx
  src/components/newdiary/SelectPicture.jsx
  src/hooks/useCheckAvailability.jsx
  src/hooks/useDiaryActions.js
  src/pages/Home.jsx
  src/pages/Notification.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Register.jsx
  src/pages/mypage/MyPageSetting.jsx
  src/pages/mypage/Mypage.jsx
Labels: 🔨 Refactor

#336 refactor: BuddyCard 컴포넌트 UI 로직과 절교 처리 로직 분리
  src/components/buddy/BuddyCard.jsx
  src/hooks/index.js
  src/hooks/useBuddyActions.js
Labels: 🔨 Refactor

#337 bugfix : 단짝 사이에 동일한 일기가 중복 교환되는 에러 수정 완료
  src/hooks/useDiaryActions.js
  src/pages/Notification.jsx
Labels: 🐞 BugFix

#342 refactor : 단짝 찾기 신청 버튼 기능 리팩토링
  src/components/buddy/BuddySearch.jsx
  src/hooks/index.js
  src/hooks/useBuddySearchAction.js
  src/pages/mypage/Mypage.jsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#343 bugfix: 교환이 완료되었거나, 교환신청이 된 건에 대한 일기를 삭제했을 경우 오류 발생 현상 해결
  src/hooks/useDiaryActions.js
Labels: 🐞 BugFix

#347 docs: 하루몽 프로젝트 README.md 작성 완료Docs/readme
  README.md
Labels: 📃 Docs

#348 feature : 아이디 찾기 기능만 일단 구현
  src/pages/auth/Login.jsx
Labels: ✨ Feature

#349 modify : 이름 수정
  README.md
Labels: 📃 Docs

#350 docs: Update README.md
  README.md
Labels: 📃 Docs
